#!/bin/bash

git submodule update --init --recursive vendor/raylib
git submodule update --init --recursive vendor/clay

git submodule update --recommend-shallow --init vendor/angle

if [ "$1" == "angle" ]; then
	sh ./bootstrap-angle
fi
